### ISSUE TITLE
molecule-simulation fails in chrome when using Wasm

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-simulation-tools#215]
It fails after clicking "load molecule". This occurs both in default canary and when enabling WASM flags in Chrome 56.

Logs:
```

firefly.min.js:21 No viewer version specified, will implicitly use @build_version@
worker.js:6 importing globa.js and simulation.js
three.min.js:2 THREE.WebGLRenderer 71
firefly.min.js:1 ID buffer requested, but MRT is not supported. Some features will not work.
:5000/lammps/worker.js:6 importing globa.js and simulation.js
localhost/:1 [.Offscreen-For-WebGL-0x7fc406801a00]RENDER WARNING: there is no texture bound to the unit 1
localhost/:1 [.Offscreen-For-WebGL-0x7fc406801a00]RENDER WARNING: there is no texture bound to the unit 2
worker.js:9 importing emscripten.js
:5000/lammps/worker.js:9 importing emscripten.js
:5000/favicon.ico Failed to load resource: the server responded with a status of 404 (File not found)
emscripten.js:125 trying binaryen method: native-wasm
:5000/lammps/emscripten.js:125 trying binaryen method: native-wasm
emscripten.js:122 Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
emscripten.js:125 Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
:5000/lammps/emscripten.js:122 Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
:5000/lammps/emscripten.js:125 Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)
emscripten.js:125 failed to compile wasm module: abort("Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)") at Error
    at jsStackTrace (http://localhost:5000/lammps/emscripten.js:794:12)
    at stackTrace (http://localhost:5000/lammps/emscripten.js:808:11)
    at abort (http://localhost:5000/lammps/emscripten.js:8580:43)
    at assert (http://localhost:5000/lammps/emscripten.js:332:3)
    at getBinary (http://localhost:5000/lammps/emscripten.js:1170:4)
    at doNativeWasm (http://localhost:5000/lammps/emscripten.js:1215:63)
    at Object.Module.asm (http://localhost:5000/lammps/emscripten.js:1331:19)
    at http://localhost:5000/lammps/emscripten.js:8304:1
    at http://localhost:5000/lammps/worker.js:10:1
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
emscripten.js:125 trying binaryen method: asmjs
:5000/lammps/emscripten.js:125 failed to compile wasm module: abort("Assertion failed: on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)") at Error
    at jsStackTrace (http://localhost:5000/lammps/emscripten.js:794:12)
    at stackTrace (http://localhost:5000/lammps/emscripten.js:808:11)
    at abort (http://localhost:5000/lammps/emscripten.js:8580:43)
    at assert (http://localhost:5000/lammps/emscripten.js:332:3)
    at getBinary (http://localhost:5000/lammps/emscripten.js:1170:4)
    at doNativeWasm (http://localhost:5000/lammps/emscripten.js:1215:63)
    at Object.Module.asm (http://localhost:5000/lammps/emscripten.js:1331:19)
    at http://localhost:5000/lammps/emscripten.js:8304:1
    at http://localhost:5000/lammps/worker.js:10:1
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
:5000/lammps/emscripten.js:125 trying binaryen method: asmjs
emscripten.js:125 binaryen method succeeded.
:5000/lammps/emscripten.js:125 binaryen method succeeded.
viewer.js:77 VIEWER: Inside molview initialized
viewer.js:78 6973
worker.js:158 command: timestep 0.5
molview.min.js:4 cPromise resolved
molview.min.js:3 2 ms to build arrays
firefly.min.js:19 undefined
viewer.js:32 VIEWER: About to change representation!
nanocore.min.js:9 saveSession Socket-ID is  C8E6AA2B-25D7-40D5-B0C0-D7D264AA492A
simulation.js:4 Uncaught TypeError: Module.get_dir_path is not a function
    at create_simulation_box (simulation.js:4)
    at onmessage (worker.js:39)
:5000/lammps/worker.js:158 command: timestep 0.5
worker.js:159 Uncaught TypeError: Module.exec_cmd is not a function
    at onmessage (worker.js:159)
simulation.js:27 Uncaught TypeError: Module.apply_nvt_settings is not a function
    at fix_nvt (simulation.js:27)
    at onmessage (worker.js:65)
simulation.js:51 Uncaught TypeError: Module.run_simulation is not a function
    at trigger_dynamics (simulation.js:51)
    at onmessage (worker.js:92)
:5000/checkS3Url/94604504d07c7ec9d9b83d7fbd3dc798 Failed to load resource: the server responded with a status of 404 (File not found)
firefly.min.js:1 Unable to find VR supported display.
:5000/savesession/ Failed to load resource: the server responded with a status of 501 (Unsupported method ('POST'))
nanocore.min.js:9 error  501
nanocore.min.js:9 There was an error saving the session: Error: Status code 501
    at XMLHttpRequest.i.onload (nanocore.min.js:9)
:5000/lammps/simulation.js:4 Uncaught TypeError: Module.get_dir_path is not a function
:5000/lammps/worker.js:159 Uncaught TypeError: Module.exec_cmd is not a function
:5000/lammps/simulation.js:27 Uncaught TypeError: Module.apply_nvt_settings is not a function
:5000/lammps/simulation.js:51 Uncaught TypeError: Module.run_simulation is not a function
firefly.min.js:1 ID buffer requested, but MRT is not supported. Some features will not work.
﻿```

**Comment by dane1122** [comment]
Fixed in commit #43769ba6cb7b62e7232415efc7b21bfb0a9b291c
